---

- name: AAP Backup
  hosts: controller
  gather_facts: no
  become: yes
  tasks:

  - name: Include Backup and Restore variables
    include_vars: main.yml

  - name: Perform AAP backup
    command:
      cmd: "{{ aap_backup_cmd }}"
      chdir: "{{ aap_base_folder }}"
  
  - name: Find AAP backup files
    find:
      paths: "{{ aap_base_folder }}"
      patterns: "{{ aap_backup_prefix }}"
      file_type: any
    register: _files_to_move

  - name: Copy AAP backup files to backup folder
    copy:
      remote_src: true
      src: "{{ item.path }}"
      dest: "{{ aap_backup_folder }}"
    with_items: "{{ _files_to_move.files }}"

  - name: Remove AAP backup files from folder
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ _files_to_move.files }}"

