---

- name: AAP Backup
  hosts: controller
  gather_facts: no
  become: yes
  tasks:

  - name: Include Backup and Restore variables
    include_vars: main.yml

  - name: Perform AAP backup
    command:
      cmd: "{{ aap_backup_cmd }}"
      chdir: "{{ aap_base_folder }}"
  
  - name: Find AAP backup files
    find:
      paths: "{{ aap_base_folder }}"
      patterns: "{{ aap_backup_prefix }}"
      register: _files_to_move
  - debug:
      var: _files_to_move

  # - name: Move AAP backup files to backup folder
  #   command: 
  #     cmd: "mv -f {{ aap_base_folder }}{{ aap_backup_prefix}} {{ aap_backup_folder }}"
