---

- name: AAP Backup
  hosts: controller
  gather_facts: no
  become: yes
  tasks:

  - name: Include Backup and Restore variables
    include_vars: main.yml

  - name: Perform AAP backup
    command:
      cmd: "{{ aap_backup_cmd }}"
      chdir: "{{ aap_base_folder }}"
  
  - name: Move AAP backup files to folder
    command: 
      cmd: "mv -f {{ aap_base_folder }}{{ aap_backup_prefix}} {{ aap_backup_folder }}"
